[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "filetype"
ignore_missing_imports = true

[tool.pylint.MASTER]
disable = [
    "missing-module-docstring"
]
